{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "logitech-media-server.fullname" . }}-data
  labels:
    {{- include "logitech-media-server.labels" . | nindent 4 }}
  {{- if .Values.persistence.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.persistence.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes: {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- include "logitech-media-server.storageClass" . | nindent 2 }}
{{- end -}}
